version: "3.6"
services:
    zoffline:
         image: qvotan/zoffline:${IMAGE_TAG}
         build:
             context: .
             dockerfile: Dockerfile
         container_name: zoffline
         environment:
            - TZ=Europe/London
         volumes:
            - /home/ubuntu/zwift_storage/storage/:/usr/src/app/zwift-offline/storage
         ports:
            - 8081:80
            - 443:443
            - 3024:3024/udp
            - 3025:3025
            - 5353:53/udp
         restart: unless-stopped
